version: "1.0"
services:
  news-aggregator:
    build: .
    container_name: newsAggregator
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true